spring.application.name=mcart-product-service

#spring.data.mongodb.uri=mongodb://localhost:27017/mcart
spring.data.mongodb.uri=mongodb+srv://shubhamagg2795_db_user:Test123@mcart-cluster.1iemsvo.mongodb.net/mcart?retryWrites=true&w=majority&appName=mcart-cluster
#spring.data.mongodb.uri=${MONGO_URI}

# OpenSearch - disabled by default, enable on demo day
opensearch.enabled=false
opensearch.host=${OPENSEARCH_HOST:localhost}
opensearch.port=443
opensearch.username=${OPENSEARCH_USER:admin}
opensearch.password=${OPENSEARCH_PASS:admin}
opensearch.scheme=https

# Cognito JWT
cognito.jwk-set-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_w11q1SuUr/.well-known/jwks.json