spring.application.name=mcart-product-service
#spring.data.mongodb.uri=mongodb://localhost:27017/mcart
spring.data.mongodb.uri=mongodb+srv://shubhamagg2795_db_user:Test123@mcart-cluster.1iemsvo.mongodb.net/mcart?retryWrites=true&w=majority&appName=mcart-cluster

