name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "target/productservice-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/"

      - name: Deploy and Restart Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set +e

            echo "Stopping old application..."
            pkill -9 -f productservice-0.0.1-SNAPSHOT.jar || echo "No running process found"

            sleep 2

            echo "Replacing jar..."
            cp /home/ubuntu/target/productservice-0.0.1-SNAPSHOT.jar /home/ubuntu/productservice-0.0.1-SNAPSHOT.jar

            echo "Starting new application..."
            cd /home/ubuntu
            setsid java -jar productservice-0.0.1-SNAPSHOT.jar > app.log 2>&1 < /dev/null &

            sleep 5
            pgrep -f productservice-0.0.1-SNAPSHOT.jar && echo "SUCCESS: App is running!" || echo "FAILED: App did not start"

            echo "Deployment completed"